services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
  
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    #env_file:
    #  - .env.deploy
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongodb_data:
